// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6J92xjnqOSdthqMs-0xRdiVcqPEwKDOM',
    appId: '1:1074730233614:web:213ae99cd4598978c9b15f',
    messagingSenderId: '1074730233614',
    projectId: 'book-d8295',
    authDomain: 'book-d8295.firebaseapp.com',
    storageBucket: 'book-d8295.firebasestorage.app',
    measurementId: 'G-2JSBR7F37Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfvIe5G2vA1PqevpZTX0olR7nwgXm7yRU',
    appId: '1:1074730233614:android:198efdc324840679c9b15f',
    messagingSenderId: '1074730233614',
    projectId: 'book-d8295',
    storageBucket: 'book-d8295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKFAlpsBVk3s8YdswjC5DqhmNAhSgbeN0',
    appId: '1:1074730233614:ios:8e30e7b7006aa970c9b15f',
    messagingSenderId: '1074730233614',
    projectId: 'book-d8295',
    storageBucket: 'book-d8295.firebasestorage.app',
    iosClientId: '1074730233614-n52cla5itsop9mqh46tma3svceg8qd32.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKFAlpsBVk3s8YdswjC5DqhmNAhSgbeN0',
    appId: '1:1074730233614:ios:8e30e7b7006aa970c9b15f',
    messagingSenderId: '1074730233614',
    projectId: 'book-d8295',
    storageBucket: 'book-d8295.firebasestorage.app',
    iosClientId: '1074730233614-n52cla5itsop9mqh46tma3svceg8qd32.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookapin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6J92xjnqOSdthqMs-0xRdiVcqPEwKDOM',
    appId: '1:1074730233614:web:c2369245fb0a39b6c9b15f',
    messagingSenderId: '1074730233614',
    projectId: 'book-d8295',
    authDomain: 'book-d8295.firebaseapp.com',
    storageBucket: 'book-d8295.firebasestorage.app',
    measurementId: 'G-HCPW4NBMWN',
  );
}
